### ISSUE TITLE
use with docker

### ISSUE THREAD

**Issue by baracoder** [firehol/firehol#114] opened 2015-12-21 17:24 UTC
Hello,

i would like to use firehol with docker. Docker creates and manages a chain called "DOCKER" and a forward rule to direct all traffic to this chain.

Is it possible to configure firehol to ignore the DOCKER chain an the forward rule on start/stop?

**Comment by udomsak** [comment] 2016-08-25 10:48
May be not  fault of firehol  or change issue to feature request  for docker support  

## docker  iptables need ( may be i am wrong ) but i fix it work 

- nat
- filter 

@baracoder  Please add something like this 

```sh
interface docker0 docker
        client all accept
        server all accept

router docker2internet inface docker0 outface eth1
    masquerade
    route all accept

iptables -t nat -N DOCKER
iptables -t filter -N DOCKER
```

**Comment by kaotika** [comment] 2016-09-08 16:11
I try to use firehol with docker and can't make it working. I disabled dockers iptable interaction with --iptables=false. If i activate firehol I doesn't have access to a hosted webcontainer (port 80 and 443). The webcontainer is working if i disable firehol. Any suggestions?

my firehol.conf
```
version 5

local_allowed="127.0.0.1"

interface eth0 world
	client all	accept
	server all	accept

interface docker0 docker
	client all accept
	server all accept

router docker2internet inface docker0 outface eth0
	masquerade
	route all accept

iptables -t nat -N DOCKER
iptables -t filter -N DOCKER
iptables -N DOCKER-ISOLATION
```

**Comment by ktsaou** [comment] 2016-09-08 23:40
You should have iptables logs of packets being dropped. Can you post a few of them here?

**Comment by kaotika** [comment] 2016-09-09 09:09
I hope this are the right log entries (from kern.log)
```
Sep  9 09:00:13 hostname kernel: [52457.953077] PASS-unknown:IN=docker0 OUT=docker0 PHYSIN=veth844242f PHYSOUT=veth26ad656 MAC=02:42:ac:11:00:05:02:42:ac:11:00:04:08:00 SRC=172.17.0.4 DST=172.17.0.5 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=60916 DF PROTO=TCP SPT=45470 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0
Sep  9 09:00:14 hostname kernel: [52458.952287] PASS-unknown:IN=docker0 OUT=docker0 PHYSIN=veth844242f PHYSOUT=veth26ad656 MAC=02:42:ac:11:00:05:02:42:ac:11:00:04:08:00 SRC=172.17.0.4 DST=172.17.0.5 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=60917 DF PROTO=TCP SPT=45470 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0
```

Docker creates some virtual network devices (veth*), do I have to add some rules for them?

**Comment by ktsaou** [comment] 2016-09-09 14:00
hm... it seems you need this:

```
router docker2docker inface docker0 outface docker0
policy accept
```

**Comment by daenney** [comment] 2016-11-06 12:42
I've figured out a few things w.r.t Docker. My config looks like this:
```
interface docker0 docker
        client all accept
        server all accept

router docker2internet inface docker0 outface enp7s0f1
        masquerade
        route all accept

router docker2lan inface docker0 outface enp7s0f0
        route all accept

router lan2docker inface enp7s0f0 outface docker0
        route all accept

iptables -t nat -N DOCKER
iptables -t filter -N DOCKER
iptables -N DOCKER-ISOLATION
```

This allows anything plugged in on `docker0` to work as expected. However, we get an extra layer of confusion once we insert Docker Compose into the mix since it creates and manages networks for you.

So in my case I have one Compose network that use `172.18.0.0/16` as its range so I had to add the following to be able to talk back and forth with anything running on the host or bound on the bridge IP.
```
iptables -I INPUT -s 172.18.0.0/16 -j in_docker
iptables -I OUTPUT -d 172.18.0.0/16 -j out_docker
```

I'm stuck with two more issues though:

1. How do I give the containers in the 127.18.0.0/16 network internet access?
2. Whenever I restart firehol all my containers lose network access b/c the rules inserted by Docker (Compose) are wiped.

**Comment by ktsaou** [comment] 2016-11-06 12:49
You can replace this:

```
interface docker0 docker
        client all accept
        server all accept
```

with this:

```
interface docker0 docker
        policy accept
```

Before inserting the iptables rules by hand or when you restart firehol and all your containers loose network access, you should have iptables logs. Can you post a few of them?

**Comment by ktsaou** [comment] 2016-11-06 12:52
Can you help me setup a docker environment like yours? Are there any containers I could install to emulate your situation?

**Comment by daenney** [comment] 2016-11-06 13:48
I've shared some of my Docker compose configs here: https://github.com/daenney/monitoring. That's basically the environment with the `172.18.0.0/16` network that I was talking about previously. My host runs Docker engine 1.12(.3) as available in the Docker repo and Compose 1.8.1

**Comment by ktsaou** [comment] 2016-11-06 15:35
> Do you mean the regular stuff that ends up in syslog showing the drops etc?

yes, when firehol runs, all packets indirectly dropped (i.e. not dropped directly by a configuration statement), are logged.

**Comment by jonnyt886** [comment] 2017-07-17 15:22
This is an old ticket, but these were my logs:

`[15497.314010] PASS-unknown:IN=br-752671a1924e OUT=br-752671a1924e PHYSIN=veth0f5ba84 PHYSOUT=vethdfd2c33 MAC=02:42:ac:15:00:07:02:42:ac:15:00:08:08:00 SRC=172.21.0.8 DST=172.21.0.7 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=30016 DF PROTO=TCP SPT=38162 DPT=3002 WINDOW=29200 RES=0x00 SYN URGP=0                            
[15498.331318] PASS-unknown:IN=br-752671a1924e OUT=br-752671a1924e PHYSIN=veth0f5ba84 PHYSOUT=vethdfd2c33 MAC=02:42:ac:15:00:07:02:42:ac:15:00:08:08:00 SRC=172.21.0.8 DST=172.21.0.7 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=30017 DF PROTO=TCP SPT=38162 DPT=3002 WINDOW=29200 RES=0x00 SYN URGP=0                            
[15500.358018] PASS-unknown:IN=br-752671a1924e OUT=br-752671a1924e PHYSIN=veth0f5ba84 PHYSOUT=vethdfd2c33 MAC=02:42:ac:15:00:07:02:42:ac:15:00:08:08:00 SRC=172.21.0.8 DST=172.21.0.7 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=30018 DF PROTO=TCP SPT=38162 DPT=3002 WINDOW=29200 RES=0x00 SYN URGP=0                            
[15504.411514] PASS-unknown:IN=br-752671a1924e OUT=br-752671a1924e PHYSIN=veth0f5ba84 PHYSOUT=vethdfd2c33 MAC=02:42:ac:15:00:07:02:42:ac:15:00:08:08:00 SRC=172.21.0.8 DST=172.21.0.7 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=30019 DF PROTO=TCP SPT=38162 DPT=3002 WINDOW=29200 RES=0x00 SYN URGP=0`

Thus I added this:

`docker_brs="br-+"

router dockerbridge inface $docker_brs outface $docker_brs
    policy accept`

...in addition to the `interface` mentioned above.

**Comment by DeadZen** [comment] 2017-09-19 23:03
@jonnyt886 Did you ever get it to work?

**Comment by jonnyt886** [comment] 2017-09-20 11:20
@DeadZen I had some success but it wasn't totally smooth. I use `docker-compose` and am regularly rebuilding and restarting containers. I've now reverted to running with no firewall on my development system and running it only on trusted networks when I'm using Docker.

If I remember correctly, connecting to the containers from the host system worked swell, the problem was containers communicating with each other. The `br-+` above was my attempt to fix that but I think I only have half of the solution.

**Comment by ktsaou** [comment] 2017-09-20 21:39
I have added a basic helper called `docker_bridge`. Check it at PR #262

**Comment by ktsaou** [comment] 2017-09-26 18:56
merged it.
I am closing this, but if you face issues with it, just post.

**Closed by ktsaou** 2017-09-26 18:56 UTC

**Comment by xtra-be** [comment] 2017-10-18 08:30
is this allready available in the rpm releases?

**Comment by simonszu** [comment] 2018-03-06 15:42
I have an issue/question. How do you use this helper with docker-compose? Currently docker-compose spins up one network/interface per service which isn't bridged to the docker0 interface. For example, i have one service which is part of this interface:

```
5874: br-ede8d6cfb38e: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:fe:42:9c:64 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-ede8d6cfb38e
       valid_lft forever preferred_lft forever
    inet6 fe80::42:feff:fe42:9c64/64 scope link
       valid_lft forever preferred_lft forever
```
and has the IP 172.19.0.2. I think that i just have to define a second `docker_bridge br-ede8d6cfb38e 172.19.0.0/???` (don't know the subnet size) and then 

```
interface br-ede8d6cfb38e docker
client all accept
server all accept
```
since this is what i'm doing with the `docker0` interface.

Is that correct? The problem is: I do neither know the interface name (the part after the `br-` seems to be some kind of randomized UID) nor the subnet, so i have to check each service after creatin with attaching a terminal to a docker container. This is not very elegant and requires quite a lot of manual work. 

However, docker itself has declared the `link` feature deprecated and says that one has to use several networks on its own, like docker-compose does. 

Maybe there is a more elegant way like to say that all subnets in `172.x.x.x` are docker subnets or something? I do not know. What's best practice for this?

**Comment by nsteinmetz** [comment] 2018-04-18 09:44
Seems I found an acceptable solution with docker iptables mode enabled and a docker swarm cluster:

```
interface4 eth0 world
    policy drop
    client all accept
    server icmp accept
    server ping accept
    server http accept
    server https accept

interface4 eth1 vrack
    policy drop
    client all accept
    server multicast accept
    server icmp accept
    server ping accept
    server http accept
    server https accept
    server mysql accept
    server ssh accept
    server docker_container_discovery accept
    server docker_ingress accept
    server docker_host accept
    server docker_remote accept
    server docker_logstash accept
    server all accept inface docker_gwbridge

interface4 docker_gwbridge docker_bridge
    policy accept

interface4 docker0 docker_0
    policy accept

router docker2docker inface docker0 outface docker0
    policy accept

router dockergw2dockergw inface docker_gwbridge outface docker_gwbridge
    policy accept
```

To be confirmed - thanks for the hints above.
