### ISSUE TITLE
Hyphen not working in domain name

### ISSUE THREAD

**Issue by de-es** [firehol/firehol#200] opened 2017-02-08 14:22 UTC
Hyphens in domain names get erroneously converted to a range.

I was trying to set up the following rule in ` firehol.conf ` and couldn't find a way to escape the domain name properly.

```
# Let’s Encrypt
client https accept dst acme-v01.api.letsencrypt.org
```

This rule is converted to

```
-A out_internet -p tcp --sport 32768:61000 -m iprange --dst-range acme-staging.api.letsencrypt.org --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
```

but should be

```
-A out_internet -d 23.201.183.110/32 -p tcp -m tcp --sport 32768:61000 --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
```

Using firehol 3.1.1+ds-1 on Debian Jessie. If I remember right, it was working flawlessly with 1.297-1.

**Comment by philwhineray** [comment] 2017-02-09 21:29
Closing as a duplicate of #199 

Same advice, really: I will try to fix this before long but really, you should reconsider use of DNS names in your firewall config: it quite possibly isn't doing exactly what you think it is.

**Closed by philwhineray** 2017-02-09 21:29 UTC
